### ISSUE TITLE
No value in cluster tag

### ISSUE THREAD

**Issue by BlueAceTS** [cblomart/vsphere-graphite#10]
Hi, there is a typo in vsphere.go on line 355.
Wrong: if parmor.Type == "ClusterComputeRessource" {
Correct: if parmor.Type == "ClusterComputeResource" {

It's only on "s" in ClusterComputeResource.

Regards
Torsten

**Comment by cblomart** [comment]
I corrected the code, i those case don"t hesitate to propose a pull request.
Thanks anyways!
