### ISSUE TITLE
Elastic backend authentication

### ISSUE THREAD

**Issue by astronode** [cblomart/vsphere-graphite#106]
Currently Graphite doesn't seem to support auth to elasticsearch so there is no way to push data to a secured cluster. Would be good to add this functionality.

**Comment by MnrGreg** [comment]
We use the elastic client library from olivere which supports authentication. Please indicate what configuration you've used and what trouble you're having.

Below is an example of the yaml config required.

```
  "Backend": {
    "Type": "elastic",
    "Database": "vsphere-graphite",
    "Hostname": "elasticserver",
    "Port": 9200,
    "Encrypted": true,
    "Username": "username",
    "Password": "password"
  },
```

**Comment by astronode** [comment]
OK, I've tried this but getting another error now -

`2019/11/14 09:01:26 backend elastic: initializing
2019/11/14 09:01:26 backend elastic: 192.168.1.1:9200/vsphere-graphite-2019.11.14
2019/11/14 09:01:27 elastic: error creating elastic index vsphere-graphite-2019.11.14 - elastic: Error 400 (Bad Request): Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [doc : {properties={Timestamp={format=epoch_second, type=date}}}] [type=mapper_parsing_exception]
2019/11/14 09:01:27 Could not initialize backend Error:  elastic: Error 400 (Bad Request): Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [doc : {properties={Timestamp={format=epoch_second, type=date}}}] [type=mapper_parsing_exception]
`

**Comment by cblomart** [comment]
This could be due that you have an elastic search 7 backend and the code is still made for es 6.

Do you have the possibility to try with Es 6?

**Comment by astronode** [comment]
Unfortunately no Es6 available. How much work is it to tweak for es7?
Seems to be related to the deprecated mapping parameter.

**Comment by cblomart** [comment]
Linked to #96

**Comment by cblomart** [comment]
Will close in favoir of #96 to track for v1.0
