### ISSUE TITLE
Config Question about Summary Metrics

### ISSUE THREAD

**Issue by DirkFries** [cblomart/vsphere-graphite#107]
Hi @all,

I wanted to collect metrics to count my running VMS and my total VMs.

So I put 2 summary Metrics in the "HostSystem" section

    "ObjectType": [ "HostSystem" ],
      "Definition": [
        { "Metric": "cpu.usage.average", "Instances": "*" },
        { "Metric": "cpu.utilization.average", "Instances": "*" },
        { "Metric": "summary.numberrunningvms.latest", "Instances": "*" },
        { "Metric": "summary.totalnumbervms.latest", "Instances": "*" },
        { "Metric": "mem.usage.average", "Instances": "*" }

Unfortunaly all my vcenters tell me, that don't find that metric.

vcenter2: metric key was not found summary.numberrunningvms.latest
vcenter2: metric key was not found summary.totalnumbervms.latest

I'm sure it's just a configuration error of mine, but I just can't find it.
Maby someone has a hint for me ?

Thanks a lot !

**Comment by cblomart** [comment]
I need to check, but I suspect the summary metrics are not available on the realtime metrics, only on the rolled-up metrics.
