### ISSUE TITLE
Stability when querying multiple vcenters

### ISSUE THREAD

**Issue by DirkFries** [cblomart/vsphere-graphite#108]
Hi cblomart,

I am collecting metrics from 4 different vcenters with vsphere-graphite (2019/12/05 09:50:42 Version information: NA - aba709b@HEAD (dirty)) at the moment.

Lately one of those vcenters had problems to connect to all of its host because of packet loss. Of course I was missing metrics during the time of packet loss from this certain vcenter, but I am also missing all metrics from the 3 other vcenters during these periods (the 3 didn't have any connection problem at all at that time). By accident the faulty vcenter was also in the first line of the config file.

Is there a way to configure a timeout per vcenter so that I can collect metrics from the other 3 if one fails ?

Bye, Dirk

**Comment by cblomart** [comment]
Sorry for the delay.

vsphere-graphite should interrogate vcenters in // so the timeout shouldn't help with your issue.

Cédric
