### ISSUE TITLE
No cluster (vsphere) output only host,vm and datastore.

### ISSUE THREAD

**Issue by onnan** [cblomart/vsphere-graphite#110]
Hi, I'm currently running vpshere-graphite with a Prometheus backend. While I imported som dashboards in Grafana made by the community I noticed that the refer vsphere metrics. However in the scaper output there is only metrics for vmware_vm*, vmware_host* and vmware_datastore. 

My config.json looks like this:

`{
  "Domain": "localdomain",
  "ReplacePoint": false,
  "Properties": [ "all" ],
  "Interval": 60,
  "FlushSize": 1000,
  "VCenters": [
    { "Username": "_username_", "Password": "_password_", "Hostname": "_vcenter_" }
  ],
  "Backend": {
    "Type": "prometheus",
    "Hostname": "localhost",
    "Port": 9090,
    "Encrypted": false
  },
  "Metrics": [
    {
      "ObjectType": [ "VirtualMachine", "HostSystem" ],
      "Definition": [
        { "Metric": "cpu.usage.average", "Instances": "" },
        { "Metric": "cpu.usage.maximum", "Instances": "" },
        { "Metric": "cpu.usagemhz.average", "Instances": "" },
        { "Metric": "cpu.usagemhz.maximum", "Instances": "" },
        { "Metric": "cpu.totalCapacity.average", "Instances": "" },
        { "Metric": "mem.usage.average", "Instances": "" },
        { "Metric": "mem.usage.maximum", "Instances": "" },
        { "Metric": "mem.consumed.average", "Instances": "" },
        { "Metric": "mem.consumed.maximum", "Instances": "" },
        { "Metric": "mem.active.average", "Instances": "" },
        { "Metric": "mem.active.maximum", "Instances": "" },
        { "Metric": "mem.vmmemctl.average", "Instances": "" },
        { "Metric": "mem.vmmemctl.maximum", "Instances": "" },
        { "Metric": "mem.totalCapacity.average", "Instances": "" }
      ]
    },
    {
      "ObjectType": [ "VirtualMachine" ],
      "Definition": [
        { "Metric": "virtualDisk.totalWriteLatency.average", "Instances": "*" },
        { "Metric": "virtualDisk.totalReadLatency.average", "Instances": "*" },
        { "Metric": "virtualDisk.numberReadAveraged.average", "Instances": "*" },
        { "Metric": "virtualDisk.numberWriteAveraged.average", "Instances": "*" },
        { "Metric": "cpu.ready.summation", "Instance": ""}
      ]
    },
    {
      "ObjectType": [ "HostSystem" ],
      "Definition": [
        { "Metric": "disk.maxTotalLatency.latest", "Instances": "" },
        { "Metric": "disk.numberReadAveraged.average", "Instances": "*" },
        { "Metric": "disk.numberWriteAveraged.average", "Instances": "*" }
      ]
    }
  ]
}
`

**Comment by cblomart** [comment]
I suppose you mean that there are no datastore metrics?

vsphere-graphite works on realtime metrics. Unfortunately, these metrics don't exist on the datastore level.
