### ISSUE TITLE
Map network metrics to network name

### ISSUE THREAD

**Issue by dupondje** [cblomart/vsphere-graphite#111]
Hi,

When getting VM network stats (net.received.average), the instance is 4000, 4001, etc for example.
It would be nice if we could map it to the network name. Cause 4000, 4001 etc doesn't say anything :)

Been looking at it today, but couldn't get a proper link between the 4000 and the network name.

**Comment by cblomart** [comment]
These are the reference to the vnet.
You would need to parse the hardware configuration of the cam to find back the vnet informations.

**Comment by dupondje** [comment]
Couldn't find the right way to do it yet.
Any chance you could get it fixed? :)

**Comment by cblomart** [comment]
retrieving this information could be costly...
