### ISSUE TITLE
Q: Run second process on different port ?

### ISSUE THREAD

**Issue by DirkFries** [cblomart/vsphere-graphite#114]
Hi,

I need to run a second vsphere-graphite on the same host due to different vcenter versions.

I tried to set a different port to listen on in the json file like this:

 "Backend": {
    "Type": "thinprometheus",
    "Hostname": "127.0.0.1",
    "Port": 9998,
    "Encrypted": false
  },

But if I start the binary it stills try to listen on 9999.

Does anyone have a hint for me ?
Thanks !

Bye, Dirk

**Comment by cblomart** [comment]
Do you have issues with different versions of vcenter in the same vsphere-graphite ?

You did say it still listens on port 9999 although the default port is 9155.
So it looks like it loads its config from the same file.

I guess your config file is in /etc ?

The behavior of vsphere-graphite is to look for the config file first in /etc then in the current folder.

So be sure that the config file is not in /etc and to start vsphere-graphite by starting it in the folder containing the proper config file. -I hope this makes sense-

When using container the simple solution is to map the correct config file to /etc/vsphere-graphite.json.

**Comment by DirkFries** [comment]
Hi Cedric,

shame on me. In fact I had the config file in a different directory, but months ago I had made a symlink to that file in /etc. That's where the trouble came from. Now everything works fine!

The issue I have is that an older vcenter of the 4 ones I query does not have a certain metrictype. So vsphere-graphite failed to get metrics from any ot the 4 vcenters. So my idea was to start 2 instances with different confis.

Thanks a lot !

**Comment by cblomart** [comment]
No problem! i will close this one and open another issue because vsphere-graphite should support having different vcenter with different metric definitions. (i tought there was already an issue on this but can't find it back).
