### ISSUE TITLE
no metrics indexed

### ISSUE THREAD

**Issue by mareban** [cblomart/vsphere-graphite#123]
Hello,

vsphere-graphite works well for indexing clusters, hosts, vms and datastore (fluentd+elasticsearch 7.6.1) !

I'm using the default template but i cannot have memory or cpu metrics with my admin vsphere account !!

Have i missed something, is there some dependencies missing (i've installed govc), extra rights, or other config stuff ?

Thanks for your help.

**Comment by cblomart** [comment]
the vsphere admin account should see all metrics.

there are no dependencies but the base of govc is the same as vsphere-graphite: so if you see the metrics with govc, you must see them with vsphere-graphite.

can you share the logs of your daemon? At startup, it resolves metrics and logs those that are not found: this may help.

**Comment by cblomart** [comment]
Hello @mareban,

Did you close this because you found a solution or just because the issue was stale?

Cédric
