### ISSUE TITLE
inventory 

### ISSUE THREAD

**Issue by mareban** [cblomart/vsphere-graphite#131]
Hello,

Is it possible to retrieve some VM properties like number of cpu, status (started or not), ip address, disk size, memory allocated, Os, .... with vsphere-graphite, and if it is possible how to configure the vphere-graphite.json please ?

Thanks for your help.

**Comment by cblomart** [comment]
From the readme:

 ```
You can select the extra data collected by using the "Properties" property:

datastore: reports the datastores associated with a virtual machine
host: reports the host the virtual machine runs on
cluster: reports the cluster the virtual machine is in
network: reports the network the virtual machine is connected to
resourcepool: reports the resource pool the virtual machine is in
folder: reports the folder the virtual machine is in
tags: reports the tags associated with the virtual machine
numcpu: reports the number of virtual CPUs the virtual machine has
memorysizemb: reports the quantity of memory the virtual machine has
disks: reports the logical disk's capacity inside the virtual machine
all: reports all the information
```

Some of the information you mentioned are not collected: status (powered on, powered-off, suspended), OS, and IP addresses.

Would you feel that properties collection would be more complete with these?

**Comment by mareban** [comment]
Thanks a lot, i think it is good enough,  i can have the other info with getvmsbycluster.py from pyvmomi samples to get the status, OS, IP address too :-) 

Tag is a quite nice info, we are using them to have extra metadata for our virtual environnement !

Thanks for this great project.

**Comment by cblomart** [comment]
Sorry for the info but tags are still limited as they are not the ones available via rest app 🙁
