### ISSUE TITLE
no active connection found: no Elasticsearch node available

### ISSUE THREAD

**Issue by djbshort** [cblomart/vsphere-graphite#137]
We try to configure the module with elastic as backend and get the following error:

`Nov 19 15:47:02 linuxserver01 systemd[1]: Starting send vsphere stats to graphite...
Nov 19 15:47:02 linuxserver01 systemd[1]: Started send vsphere stats to graphite.
Nov 19 15:47:02 linuxserver01 vsphere-graphite[115901]: 2020/11/19 15:47:02 Version information: NA - NA@NA (NA)
Nov 19 15:47:02 linuxserver01 vsphere-graphite[115901]: 2020/11/19 15:47:02 Starting daemon: vsphere-graphite
Nov 19 15:47:02 linuxserver01 vsphere-graphite[115901]: 2020/11/19 15:47:02 main: requested properties disks, datastore, urls, host, network, folder, cluster, resourcepool, tags, numcpu, memorysizemb
Nov 19 15:47:02 linuxserver01 vsphere-graphite[115901]: 2020/11/19 15:47:02 vcenter vcenter01: initializing
Nov 19 15:47:02 linuxserver01 vsphere-graphite[115901]: 2020/11/19 15:47:02 vcenter vcenter01: connecting
Nov 19 15:47:02 linuxserver01 vsphere-graphite[115901]: 2020/11/19 15:47:02 vcenter vcenter01: disconnecting
Nov 19 15:47:02 linuxserver01 vsphere-graphite[115901]: 2020/11/19 15:47:02 backend elastic: initializing
Nov 19 15:47:02 linuxserver01 vsphere-graphite[115901]: 2020/11/19 15:47:02 backend elastic: elasticsrv.corp.local:9243/vsphere-graphite-2020.11.19
Nov 19 15:47:08 linuxserver01 vsphere-graphite[115901]: 2020/11/19 15:47:08 backend elastic: error creating client - no active connection found: no Elasticsearch node available
Nov 19 15:47:08 linuxserver01 vsphere-graphite[115901]: 2020/11/19 15:47:08 Could not initialize backend Error:  no active connection found: no Elasticsearch node available
Nov 19 15:47:08 linuxserver01 systemd[1]: vsphere-graphite.service: Main process exited, code=exited, status=1/FAILURE
Nov 19 15:47:08 linuxserver01 systemd[1]: vsphere-graphite.service: Unit entered failed state.
Nov 19 15:47:08 linuxserver01 systemd[1]: vsphere-graphite.service: Failed with result 'exit-code'.
Nov 19 15:47:08 linuxserver01 systemd[1]: vsphere-graphite.service: Service hold-off time over, scheduling restart.
Nov 19 15:47:08 linuxserver01 systemd[1]: Stopped send vsphere stats to graphite.`

the configuration in the json file looks like this:

`{
  "Domain": ".corp.local",
  "ReplacePoint": false,
  "CPUProfiling": false,
  "MEMProfiling": false,
  "Properties": [ "all" ],
  "Interval": 60,
  "FlushSize": 1000,
  "VCenterResultLimit": 500000,
  "VCenterInstanceRatio": 3.0,
  "VCenters": [
    { "Username": "CORP\\vCenterRO", "Password": "mypassword", "Hostname": "vcenter01.corp.local" }
  ],
  "Backend": {
    "Type": "elastic",
    "Database": "vsphere-graphite",
    "Hostname": "elasticsrv.corp.local",
    "Port": 9243,
    "Encrypted": true,
    "Username": "elastic",
    "Password": "myelasticpassword"
  },`

**Comment by MnrGreg** [comment]
@djbshort what version of Elastic are you connecting to?

Is network connectivity in place to all Elastic nodes?

See details on elastic connection sniffing here: https://github.com/olivere/elastic/issues/817

**Comment by cblomart** [comment]
Closing as there were not much feedback since nov. @djbshort any kind of news welcome ;-)
