### ISSUE TITLE
After a while no data...

### ISSUE THREAD

**Issue by cblomart** [cblomart/vsphere-graphite#14]
Jun 28 18:18:46 lvixprfd02 vsphere-graphite: 2017/06/28 18:18:46 Could not request perfs from vcenter: 
Jun 28 18:18:46 lvixprfd02 vsphere-graphite: 2017/06/28 18:18:46 Error:  ServerFaultCode:
Jun 28 18:18:46 lvixprfd02 vsphere-graphite: Required parameter querySpec is missing
Jun 28 18:18:46 lvixprfd02 vsphere-graphite: while parsing call information for method QueryPerf
Jun 28 18:18:46 lvixprfd02 vsphere-graphite: at line 2, column 66
Jun 28 18:18:46 lvixprfd02 vsphere-graphite: while parsing SOAP body
Jun 28 18:18:46 lvixprfd02 vsphere-graphite: at line 2, column 60
Jun 28 18:18:46 lvixprfd02 vsphere-graphite: while parsing SOAP envelope
Jun 28 18:18:46 lvixprfd02 vsphere-graphite: at line 2, column 0
Jun 28 18:18:46 lvixprfd02 vsphere-graphite: while parsing HTTP request for method queryStats
Jun 28 18:18:46 lvixprfd02 vsphere-graphite: on object of type vim.PerformanceManager
Jun 28 18:18:46 lvixprfd02 vsphere-graphite: at line 1, column 0

**Comment by Papalloon** [comment]
I running it for 7 days now, I lost some data for like 5 hours but I'm not sure why.

Did you identified how long is "a while"?

**Comment by cblomart** [comment]
I restarted it and am waiting for it...
As i had other issues with virtualvcenter I am thinking of a reconnect scenario. Although I would treat vcenter in more gentle way than influx... I place of retying to connect for three consecutive times, I would try to reconnect on every tree failures on the vcenter. So still some gap but some healing...

**Comment by cblomart** [comment]
I'll add a parameter to recycle vcenter connection also.

**Comment by cblomart** [comment]
Ok back to the blackboard: vcenter connection are not persisted. (maybe an area of improvement)

So i a first set i added some logging of:

- logout events
- no managed object found matching type of interest (infrastructure description and object to measure)
- no queries created by matching the managed objects found to the list of metrics to query

Hopefully it will give a bit more detail of what the error could be.

@Papalloon: did you see the same type of error in your logs? Especialy "Required parameter querySpec is missing"

**Comment by Papalloon** [comment]
@cblomart I don't know where the logs are to be honest. I only use the `service vsphere-graphite status -l` command.

**Comment by cblomart** [comment]
that is the right way to do it. Systemd deals with the logs they basicaly get in /var/log/message and you can search them with whatever tool you like (cat, more, grep).

**Comment by Papalloon** [comment]
![image](https://user-images.githubusercontent.com/14872178/27865386-ae512616-6192-11e7-8eb8-c114c9f8366b.png)

I will check it again if I lose the connection.

**Comment by cblomart** [comment]
I didn’t see this issue anymore.
Can I close this issue?

**Comment by Papalloon** [comment]
Yes you can ! Thank you.

2018-04-27 7:28 GMT+02:00 Blomart Cédric <notifications@github.com>:
