### ISSUE TITLE
What about the xxxx.xxxx.summation metrics?

### ISSUE THREAD

**Issue by Papalloon** [cblomart/vsphere-graphite#15]
Hello,

I'm sorry to open an issue for that, you can close it right now if you want.

Do you know what the xxxx.xxxx.summation metrics mean? I thought it was the sum of the metric during the "Interval" defined on the json file but in MS.

I'm not that sure anymore...

Thank you in advance for your help.

**Comment by cblomart** [comment]
Happy to answer any questions.

Vsphere-graphite would collect real time metrics aver the interval.

In vcenter a realtime metric has a ´collection interval' of 20s.

To have one metric per ´vsphere-graphite interval' the mean, max and sum are recalculated.

So the summation should be the sum of realtime metrics with summation as a rollup type.

Does it answer your question?

**Comment by Papalloon** [comment]
Ok, as I understand I just have to divide by 20 000 in order to get %, no matter the "Interval" defined on the json file.

Yes it does answer my question, thank you very much!

**Comment by cblomart** [comment]
I don't quite follow you. There are multiple metrics with a summation rollup.
The metric returned for them in vsphere-graphite is the sum of the metrics collected for the element.

Generaly speaking VMware uses this rollup type on purpose.

Here is the list of metrics for a vm that have this rollup type:

- cpu.ready.summation
- cpu.idle.summation
- disk.numberRead.summation
- disk.numberWrite.summation
- disk.scsiReservationConflicts.summation
- net.packetsRx.summation
- net.packetsTx.summation
- cpu.costop.summation
- cpu.maxlimited.summation
- cpu.run.summation
- net.droppedRx.summation
- net.droppedTx.summation
- net.broadcastRx.summation
- net.broadcastTx.summation
- net.multicastRx.summation
- net.multicastTx.summation

*So typicaly for cpu ready summation*

If you look at vmware definition of the stat (need to update the link to 6.0): https://www.vmware.com/support/developer/vc-sdk/visdk400pubs/ReferenceGuide/cpu_counters.html

cpu.ready.summation: "Percentage of time that the virtual machine was ready, but could not get scheduled to run on the physical CPU. CPU ready time is dependent on the number of virtual machines on the host and their CPU loads."
... but the value is expressed as a summation of milliseconds (maybe they could update the desciption).

So in the case of the metric stored in the backend by vsphere graphite, this value is the sum of the values returned by vsphere over the vsphere-graphite interval. 

So to have the actual cpu % ready KB2002181 indicated to do:

> (CPU summation value / (<chart default update interval in seconds> * 1000)) * 100 = CPU ready %

To simplify for a vsphere-graphite interval of 1 minut (default):

> (CPU summation value / (60s * 1000)) * 100 = CPU ready %
> CPU ready % = CPU summation value / 600

Would you have a cpu.ready.summation of 20000 in the vsphere-graphite backend, this means that the cpu % ready was 33.3%

**Comment by Papalloon** [comment]
![image](https://user-images.githubusercontent.com/14872178/27864794-51e6372e-6190-11e7-8a48-cc37fd0b9a60.png)

Ok, my bad, I used to divide by 60 000. I thought Grafana did the * 100 automatically.

It's now totally clear. Thank you again.

By the way, where did you find the summation metrics list?
I use this : http://www.virten.net/2015/05/which-performance-counters-are-available-in-each-statistic-level/

**Comment by cblomart** [comment]
For large amount of VMs, this could be long calculations for influx.
What would you think about a "transformation" possibility in vsphere-graphite.
Most probably on basis of a basic interpreter like https://github.com/mattn/anko (or others)

**Comment by Papalloon** [comment]
Do you know how is it possible that I get more than 750%?

![image](https://user-images.githubusercontent.com/14872178/27904246-5770423c-623c-11e7-84c9-d3b7bddb6630.png)

**Comment by cblomart** [comment]
I didn't have time to investigate the problem much.
My first guess would be to check the number of cpu the VM has (i.e. 8 vcpu)

I got the list of the stats via powercli:
> Get-StatType -Entity (get-vm '**vcenter name**') | ?{ $_ -match "\.summation$" }

**Comment by Papalloon** [comment]
Oh, I see. 
It must be the same for all cpu.xxxx.summation metrics. I should try to devide the summation metric by the number of vCPU of each VM.

**Comment by cblomart** [comment]
I am just pushing a change to have numcpu and memorysizemb as tags for virtualmachines.

**Comment by Papalloon** [comment]
Is it possible to have the LUN ID or something to identify it?

**Comment by cblomart** [comment]
LUN ID... ok we speak of cpu and the disks... the metrics does contains the Datastores the vm is stored on, this can eventually help. 
metric instances will mention the lun uuid for storage metrics.

**Comment by Papalloon** [comment]
Thank you, I will update my project!
