### ISSUE TITLE
int to int32 change in govmomi performance metric

### ISSUE THREAD

**Issue by sofixa** [cblomart/vsphere-graphite#2]
Hi, i am using a highly modified version of your code and when i had to redeploy today, i noticed a bunch of compile time errors about int and int32. Then i saw this https://github.com/vmware/govmomi/commit/f74a896d868b4504be544ef47958c6b7fcc7c1c6

This means that all ints in your code need to be changed to int32 to be compatible with the latest version of govmomi.

If you want to, i can submit a PR tomorrow.

**Comment by cblomart** [comment]
Is the goal the same? If so don't hesitate to fork and PR! Contributions
are welcome :-)



2016-04-06 17:20 GMT+02:00 Adrian Todorov <notifications@github.com>:

**Comment by sofixa** [comment]
Our usage is too specific to publish, but i'll submit a PR for int -> int32 tomorrow.
In a few weeks i'll have the time and possibility to open source parts our modifications, which include InfluxDB, and in the future, ElasticSearch outputs.

**Comment by cblomart** [comment]
Would you like more separation between the input (vsphere) and the output (here graphite)?
I can work on that if of intereset.

**Comment by cblomart** [comment]
resolved in last commit
