### ISSUE TITLE
Latest metric  value not average

### ISSUE THREAD

**Issue by icnpsd** [cblomart/vsphere-graphite#21]
Hello,
the product work fine, but i realized that value of metric isn't realtime. It's possible to force latest value and not average in the configuration file "vsphere-graphite.json"

I would like cpu.usage.latest and cpu.ready.latest

Thanks

**Comment by cblomart** [comment]
When using *.latest metrics vsphere-graphite should provide the last value from collected points (for the metric and object).

vsphere/vsphere.go:601
```go

			} else if strings.HasSuffix(metricName, ".latest") {
				value = serie.Value[len(serie.Value)-1]
			}
````

So basically it would come to adding the desired metric in the list of metrics you want to collect.

Did you see any issues/bug with that? 
Shall i provide a config file with the desired metrics added?

**Comment by cblomart** [comment]
No news since so closing the issue.
