### ISSUE TITLE
Can't connect to IP based vCenter

### ISSUE THREAD

**Issue by scaleoutsean** [cblomart/vsphere-graphite#25]
Can https://github.com/cblomart/vsphere-graphite/blob/master/vsphere/vsphere.go#L86 handle usernames like admin@vsphere.local? It seems `@` in username may be what makes it fail to connect.

I tried to escape `@` with things like `\@` and `%40`, that didn't help (the latter does work in a manually assembled URL in Web browser, but not here). 
(My password has special characters as well, I also tried escaping those).

* vSphere Graphite 0.4
* vSphere 6.5 Update 1 (vCenter is an IP address;  I have no hostnames or FQDNs)

**Comment by cblomart** [comment]
The https://github.com/cblomart/vsphere-graphite/blob/master/vsphere/vsphere.go#L84 should handle that so you don't need to escape charaters in either username or password.

**Comment by scaleoutsean** [comment]
OK, closing then, thanks. It must be something else.

**Comment by cblomart** [comment]
Sorry for the fast answer.
If you need help toubleshooting don't hesitate to recontact me.

I undestand this might be an autorization denied situation nevertheless excrept form log files might be usefull.

Could you also test with govc project? (https://github.com/vmware/govmomi/tree/master/govc)

**Comment by scaleoutsean** [comment]
No problem. I had to destroy that test environment so I couldn't provide more info, but couple days ago I heard from a colleague he came across this issue as well, and he had more time to troubleshoot - it seems the issue was related to not having DNS A records for the hosts. 

So I created an issue in our downstream repo, https://github.com/jedimt/sfcollector/issues/4, it seems it's enough to document that DNS is a requirement. If this is something that may matter to users this repo, you could document it as well.

**Comment by scaleoutsean** [comment]
Will continue to follow this in #62
