### ISSUE TITLE
Large vcenter results in - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by MnrGreg** [cblomart/vsphere-graphite#31]
Hi @cblomart

When pulling metrics from our larger vcenter (3286 objects and 59148 metrics) I get a panic error as seen below. Smaller vcenters have no issue. I'm not sure how to troubleshoot this and I can't get delve going to debug unfortunately.

I noticed the crash happens just before vsphere.go line 414. I also noticed that commenting out vsphere.go lines 276 and 277 (presumably reducing the amount of objects/metrics that need to be gather) prevents the crash.

Do you have any thoughts as to what could be causing the issue?

Great work so far!

Thanks

> 2018/05/20 20:11:00 Starting daemon: vsphere-graphite
> 2018/05/20 20:11:00 connecting to vcenter: rkvcente**
> 2018/05/20 20:11:04 Initializing elastic backend mo**
> 2018/05/20 20:11:18 Retrieving metrics
> 2018/05/20 20:11:18 Setting up query inventory of vcenter:  rkvc**
> 2018/05/20 20:11:18 connecting to vcenter: rkvce**
> 2018/05/20 20:11:29 Elastic Indexing flushed
> 2018/05/20 20:11:29 Sent 0 logs to backend
> 2018/05/20 20:11:29 Memory usage : sys=11.6M alloc=3M
> 2018/05/20 20:12:01 disconnecting from vcenter: rkvce**
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10fc2e7]
> 
> goroutine 43 [running]:
> log.(*Logger).Output(0x0, 0x2, 0xc420242330, 0x2e, 0x0, 0x0)
>         /usr/local/Cellar/go/1.10.2/libexec/src/log/log.go:153 +0x47
> log.(*Logger).Println(0x0, 0xc420878d28, 0x1, 0x1)
>         /usr/local/Cellar/go/1.10.2/libexec/src/log/log.go:188 +0x6a
> github.com/cblomart/vsphere-graphite/utils.MapObjRefs(0x194ffc0, 0xc4207ac2e0, 0xc420879918, 0xc42071c8c0, 0xc, 0xc42071c940, 0x10)
>         /Users/gmay/go/src/github.com/cblomart/vsphere-graphite/utils/utils.go:82 +0x17f
> github.com/cblomart/vsphere-graphite/vsphere.(*VCenter).Query(0xc42087bf30, 0x3c, 0xc4200b4b30, 0x9, 0xc420236000)
>         /Users/gmay/go/src/github.com/cblomart/vsphere-graphite/vsphere/vsphere.go:374 +0x247e
> main.queryVCenter(0xc4200d6760, 0x14, 0xc4200b4bc0, 0xf, 0xc4200b4bd0, 0xa, 0xc4203b7580, 0x2, 0x2, 0xc42011c840, ...)
>         /Users/gmay/go/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:45 +0x5f
> created by main.(*Service).Manage
>         /Users/gmay/go/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:152 +0xdb1
> exit status 2

**Comment by cblomart** [comment]
Problem with unitialized loggers. Solved in latest commit.

**Comment by MnrGreg** [comment]
Thanks. Working well now.
