### ISSUE TITLE
Container fails with exit code 127

### ISSUE THREAD

**Issue by mzhaase** [cblomart/vsphere-graphite#34]
When running the container with 

    docker run -t -v /etc/vsphere-graphite.json:/etc/vsphere-graphite.json cblomart/vsphere-graphite:latest

It terminates immediately. There are no logs, Status is Exited(127). Tried v0.4, which leads to the same result.

The config file used works on a different installation which uses the service instead.

**Comment by cblomart** [comment]
A build issue lead to unportable binaries.
I have solved it in the latest commit.
You should be able to run it now from the following image: cblomart/vsphere-graphite:9b74480d

Please update me if the issue is solved.

I will now look at issue #35. When solved i'll do a new release.

**Comment by mzhaase** [comment]
Yes this works. Thanks!
