### ISSUE TITLE
NumCPU  and MemorySizeMB

### ISSUE THREAD

**Issue by cblomart** [cblomart/vsphere-graphite#35]
@MnrGreg signaled that every VM metric is being captured with the NumCPU and MemorySizeMB fields. This information is already captured with the Cpu and Mem groups for each VM and results in a lot of extra storage.

**Comment by cblomart** [comment]
I don’t quite get the cpu and mem group.
À configuration flag can be set to enable/dis le fetching extra vm informations.

**Comment by cblomart** [comment]
@MnrGreg, i added a config option properties. This is described in the readme.
Looks like it works but my influx backend is currently digesting the test i made the last two days so i'll need a bit of time to confirm.
It can be tested with the docker image tagged "f4f3a5d".

**Comment by MnrGreg** [comment]
Working well on my side. I think we can close this one. Thanks.

**Comment by cblomart** [comment]
made a release of it.
