### ISSUE TITLE
include influx db backend 

### ISSUE THREAD

**Issue by cblomart** [cblomart/vsphere-graphite#4]
Looked at Influxed db lately... but after attending FOSDEM graphite session, i tought the community was still lively!

Anyway i see that @ku6pk and @oxalide are using influx as a backend so i will give influx a second shot :-P

**Comment by ku6pk** [comment]
Would highly appreciate this!

Support for datastore counters as well would be great!

**Comment by sofixa** [comment]
Yeah, an InfluxDB backend is a pretty cool idea (i wrote the one [here](https://github.com/Oxalide/vsphere-influxdb-go) by basically modifying your script to add InfluxDB, un-daemonize it and add a few extras like esxi/cluster per VM).

**Comment by cblomart** [comment]
You don't neet to use it deamonized.
The daemonification is just to ease installation as a daemon (no service file to move or copy).
Command line just work natively.

Concerning enriching information with cluster/esxi host, in a graphite vision the data was hard to set in. And given that vsphere is a multiverse (host and cluster, virtulmachine & folders, datastores, network), i choose dumbly not to implement it.

I just agregate data per cluster with a static description of the clusters using carbon-c-relay (regex based)

I will lookup at possibilities with influx, but my first goal would be to add the stats in there.

**Comment by cblomart** [comment]
Splitted sources to handle backend more  easily...

First tests for datastore not conclusive... i can't get "disk.used.latest" from a datastore...

Cédric

**Comment by cblomart** [comment]
Ok... gave my twist to influxdb backend... plz comment, feeback is really appreciated.

**Comment by ku6pk** [comment]
Hi @cblomart ,

Thanks for looking into this, where is the work for this happening?

**Comment by cblomart** [comment]
I kind of pushed everything to master and made a release (binaries availabled in the release).

I'll have to branch a bit more...

**Comment by ku6pk** [comment]
No worries, at all, will have a look, test and feed back.

**Comment by cblomart** [comment]
no... no datastores yet... i do base the stats on realtime collection. vmware doesn't have or doesn't expose realtime data about datastores.

they are available at a lower collection interval... then we would need to manage multiple collection interval from vmware and from vpshere-graphite.

realtime interval: 20s
next interval: 5mins

what you could now do with influx is query and aggregate stats about one datastore (tags)

**Comment by cblomart** [comment]
No feedback since... can i consider this satisfactory ? ;-)

**Comment by cblomart** [comment]
Ok closing this without feedback. 
Don't hesitate to comment or open new issues if new features are needed.

**Comment by ku6pk** [comment]
Apologies, I've been out of the country, and should be back this weekend to have a look at :)

**Comment by cblomart** [comment]
Ok.. so closed but i am still listening

**Comment by ku6pk** [comment]
Good so far, will continue to watch in pre-production. ;)
