### ISSUE TITLE
Prometheus Backend

### ISSUE THREAD

**Issue by dupondje** [cblomart/vsphere-graphite#41]
Hi,

Are there plans to support Prometheus as a backend?
I think as there is already a system to support multiple backends, it shouln't be to hard to support Prometheus as a backend also.

Prometheus is getting very popular, so it might be nice to have it supported!

Thanks

**Comment by cblomart** [comment]
I’ve certainly thought about Prometheus.
Seems not complicated to implement.
It means starting a basic web server and providing the stats through it.

Few point of attention I would have:
* use the backend parameters to indicate where to listen to (specific ip, or ‘*´). The same for the port to listen to.
* does Prometheus stats protocol (I need to dig up the right name) support authentication: username and password from backend config
* how to store the stats to the web server while using the less memory and still be fast enough

**Comment by dupondje** [comment]
Yea starting the webserver is as easy as importing "net/http" and "github.com/prometheus/client_golang/prometheus/promhttp"
And then just:
`+       case Prometheus:
+               //Initialize Prometheus client
+               stdlog.Println("Initializing " + backendType + " backend")
+               http.Handle("/metrics", promhttp.Handler())
+               http.ListenAndServe(":9155", nil)
+               return nil
`

- The backend parameters should indeed allow to override the default port + ip

- Its possible to set a login/password to the scrape taget (so the /metrics page that is exported). So you could set a password on the /metrics page. 
But seems like almost no exporter does this currently. (You can put something else in front of it ofcourse).

- This is the biggest question. Do you want to store the stats and just 'display' them on the /metrics page? Or will we trigger a queryVCenter for each request to /metrics (which is the correct way in Prometheus world).
You can combine both also. queryVCenter on call to /metrics, and then cache them for definedTime. If a new call arrives within the definedTime, then you can just output the cached ones. If its later, run a new queryVCenter and give those stats :)

I could start implementing this, but I guess you might be 100-times faster as my Go knowledge is almost non-exiting :smiley:

**Comment by cblomart** [comment]
The daemon already has a scheduling to fetch data. I rather leverage that that fetch data on request to /metrics.
In this sense I don’t know if using a promhttp handler is usefull.
I thought of caching gzipped representation of the data and serving that on request.

**Comment by cblomart** [comment]
Hello,

I merged your pull #43 and made some changes on the branch "add_prometheus".

Please send some feedback on it as it is not 100% equivalent to the result you had before.

Cédric

**Comment by cblomart** [comment]
Thanks for the feedback.

* is having a prefix a constraint of prometheus?
* i'll lookup why type is still there.
* instance resolving should be looked at further in issue #44. Metrics instances are linked to devices (as in physical) and not to instance (of network, datastores). I just marked the issue as enhancement.
* we changed recently the possibility to select which label is collected so you can in fact chose which labels are reported to prometheus (see readme):

> You can select the extra data collected by using the "Properties" property:
>
> * datastore: reports the datastores associated with a virtual machine
> * host: reports the host the virtual machine runs on
> * cluster: reports the cluster the virtual machine is in
> * network: reports the network the virtual machine is connected to
> * resourcepool: reports the resourcepool the virtual machine is in
> * folder: reports the folder the virtual machine is in
> * tags: reports the tags associated with the virtual machine
> * numcpu: reports the number of virtual cpus the virtual machine has
> * memorysizemb: reports the quantity of memory the virtual machine has
> * disks: reports the logical disks capacity inside the virtua machine
> * **all**: reports all the information

**Comment by dupondje** [comment]
- Its not a requirement, but its a convention. See https://prometheus.io/docs/practices/naming/
 This way you can easily see which exporter exports those metrics.
- Thx
- Yea indeed, move that there :)
- Thats only a part of the solution unfortunately. Thing is you should be able to configure if for each metric. For example on 'cpu.usage.average' I care about the host/cluster/vcenter that server is in. So I could write a query that shows me the CPU usage of all vm's on 1 host. Here it doesn't matter on which datastore or network they are on.
But for 'virtualDisk.totalWriteLatency.average', it is important to know the datastore! But network can be skipped.
And for 'net.packetsRx.summation' I would like to know the network, but not the datastore then :)

But that might be some improvement for later ...
Thing is that for each change in label, you have a new metric in Prometheus. So you will always need to have a sum() then. Also it has some storage overhead.
- Would there be a way to include cpunum and memory in a separate metric? And not in a label?
Cause its important information, but its just exported incorrectly now.

**Comment by cblomart** [comment]
The prefix shall be back.

Labels are currently considered metadata about the metric and references what we know about the managed object referenced by the metric.

I do understand that you want to know about datastore and networks for related metrics (iops, rx packets, ...). For VMware that is the role of the instance but again instances are "physical" (lun to host or vm, nic to host or vm, ...). Resolving that to other managed object is not direct but will be further looked at in the referenced issue #44.

Can you raise another issue for the numcpu and memorysizemb? I think this is effectively intersting but more generic to vsphere-graphite than related to prometheus.

**Comment by cblomart** [comment]
On the look for the lost 'Backend prometheus unknown.'

**Comment by dupondje** [comment]
Just add a case: Prometheus on https://github.com/cblomart/vsphere-graphite/blob/master/backend/backend.go#L424
:)

**Comment by cblomart** [comment]
Thanks, i added a case for it.

Would you agree this could be merged to master? If so could you still confirm it works well on your side and i'll do the same on mine.

**Comment by cblomart** [comment]
Still works in here! i will merge the new feature. Let me a couple of days to evaluate extra issues and i'll do a release.
