### ISSUE TITLE
Put numcpu and memorysizemb in its own metric

### ISSUE THREAD

**Issue by dupondje** [cblomart/vsphere-graphite#45]
Like discussed in #41 we should put numcpu and memorysizemb in its own metric.
Now its added as a label into the current metrics, which is not correct/unpractical :)

Maybe while implementing think about an option to add some metrics.
Like powerState is something I think might be useful also to add!

**Comment by cblomart** [comment]
I just pushed a change to make numcpu and memorysizemb as their own metrics.

We can talk about powerstate: how would you consider it ( integer ? powerdOn/poweredoff/suspended)

Do you think there are other interesting values? Tools, health, ...

**Comment by dupondje** [comment]
Tested it, and it looks perfect :) Thanks!

I would just copy the value the vSphere API returns 1:1 for powerState?
Also this should be a label and not a separate metric.

This because for example you want to sum all the CPU's from online VM's:
sum(vsphere_cpu_count_latest{powerstate="on"})

powerState seems the only real usefull one that is missing :)

**Comment by dupondje** [comment]
Oh! Did find some issue in the numcpu metric:
vsphere_cpu_count_latest{datastore="local002",host="esx001",instance="C:/",name="storage002",network="Public",type="virtualmachine",vcenter="vcenter001"} 4

name and instance should not be there...

**Comment by dupondje** [comment]
Sorry, name needs to be there indeed. Was confused because the vm had 'storage' in its name :)
But instance should be removed

**Comment by cblomart** [comment]
Can you check with commit 95d53ef ?
