### ISSUE TITLE
Add Cluster support

### ISSUE THREAD

**Issue by dupondje** [cblomart/vsphere-graphite#47]
An important feature request :)
We should add Cluster support!

All VM/Host metrics might be linked to a cluster, so that should be added as a label/tag on the metric.
This so we can group our metrics by cluster. Or only show metrics from 1 cluster for example in Grafana!

**Comment by cblomart** [comment]
Again, i changed a whole bunch how informations are handled. So yes still on the working bench to debug.

**Comment by cblomart** [comment]
Clusters shall be back!
