### ISSUE TITLE
http connection when using "Encrypted" value in Backend setting.

### ISSUE THREAD

**Issue by 482378** [cblomart/vsphere-graphite#48]
https://github.com/cblomart/vsphere-graphite/blob/b425f9b08d4af6537f6e13da7ecd2e0d129d7957/backend/backend.go#L75 hard coded "http://"

**Comment by cblomart** [comment]
Should be corrected in recent commit.
Please consider using thininfluxdb (i switched to it for more than one year)

**Comment by 482378** [comment]
Cool, can you please commit changes to docker rpi-vsphere-graphite image?

**Comment by cblomart** [comment]
Please be patient.
Much change has been pushed in the last few days and we have issues with elastic as well as pull for fluentd.
I'd like to project to stabilize for a few days (weeks?) before making a release.

**Comment by cblomart** [comment]
I just made a new release v0.7 the container image for rpi will show up soon.
