### ISSUE TITLE
Segfault when specifying multiple vcenters

### ISSUE THREAD

**Issue by jlothian** [cblomart/vsphere-graphite#49]
I get a segfault if I specify more than one vcenter in my JSON config.  It looks like what's happening is `stdlog` isn't defined in CleanStringMap, but I don't know enough about Go yet to give a patch, sorry.  Here's the traceback:
 
2018/07/24 17:16:15 Version information
2018/07/24 17:16:15  - Commit: b425f9b
2018/07/24 17:16:15 
2018/07/24 17:16:15 Starting daemon: vsphere-graphite
2018/07/24 17:16:15 connecting to vcenter: vcenter1.domain
2018/07/24 17:16:16 connecting to vcenter: vcenter2.domain
2018/07/24 17:16:18 Initializing elastic backend elasticsearch1.domain:9200/metricstest1-2018.07.24
2018/07/24 17:16:19 Retrieving metrics
2018/07/24 17:16:19 Setting up query inventory of vcenter:  vcenter2.domain
2018/07/24 17:16:19 connecting to vcenter: vcenter2.domain
2018/07/24 17:16:19 Setting up query inventory of vcenter:  vcenter1.domain
2018/07/24 17:16:19 connecting to vcenter: vcenter1.domain
2018/07/24 17:16:20 Issuing 31 queries to vcenter vcenter1.domain requesting 583 metrics.
2018/07/24 17:16:20 disconnecting from vcenter: vcenter2.domain
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4f9ac7]

goroutine 122 [running]:
log.(*Logger).Output(0x0, 0x2, 0xc420458300, 0x2d, 0x0, 0x0)
	/usr/lib/go-1.10/src/log/log.go:153 +0x47
log.(*Logger).Println(0x0, 0xc42056c1f0, 0x1, 0x1)
	/usr/lib/go-1.10/src/log/log.go:188 +0x6a
github.com/cblomart/vsphere-graphite/utils.CleanStringMap(0xc4203783f0, 0xc42008f500, 0x6a, 0x70)
	/home/jlothian/go/src/github.com/cblomart/vsphere-graphite/utils/utils.go:279 +0x1d0
github.com/cblomart/vsphere-graphite/vsphere.(*VCenter).Query(0xc42056df10, 0x1e, 0xc4202723c0, 0x13, 0xc42027e1c0, 0xa, 0x10, 0xc42017c080, 0xc42017c090)
	/home/jlothian/go/src/github.com/cblomart/vsphere-graphite/vsphere/vsphere.go:446 +0x363a
main.queryVCenter(0xc420296120, 0x22, 0xc420272400, 0x1b, 0xc420270550, 0x9, 0xc42001fa40, 0x2, 0x2, 0xc42019c3e0, ...)
	/home/jlothian/go/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:46 +0x97
created by main.(*Service).Manage
	/home/jlothian/go/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:170 +0xe22

**Comment by jlothian** [comment]
I think I've got it fixed in this PR - https://github.com/cblomart/vsphere-graphite/pull/50

**Comment by cblomart** [comment]
As indicated in the pull request, this was solved by simplifying logging.

Thanks for a gain for your involvement !
