### ISSUE TITLE
Metrics are Strings Field Type in InfluxDB

### ISSUE THREAD

**Issue by Papalloon** [cblomart/vsphere-graphite#6]
Hi,

I checked your code and it seems that you send the metrics as int.
Poorly it appears to be strings in InfluxDB.

I tried to change your backend ligne 152.

from `fields := make(map[string]interface{})` to `fields := make(map[integer]interface{})`

Do you know how to correct it?

**Comment by cblomart** [comment]
fields are the different fields set for the influxdb point.

Bellow (line 153?), we set the fields["value"] to the point value.

So the "string" of the map is the key, or here "value"..

**Comment by Papalloon** [comment]
Ok, so how can I send integer instead of string?
The Metrics are all int in Vsphere.

**Comment by cblomart** [comment]
In the struct "point", set the Value field type to int

**Comment by Papalloon** [comment]
I already tried that, replacing String by int64 line 23.

**Comment by Papalloon** [comment]
But nothing changed.

What I did :

1 : Turn off vsphere-graphite.service
2 : Set the Value type to int
3 : Delete de InfluxDB
4 : Recreate it
5: Turn on vsphere-graphite.service

**Comment by cblomart** [comment]
I just pushed a update to change the value to int64.

**Comment by Papalloon** [comment]
Thank you for the updates.

It works perfectly!

Integer makes more sense and it's easier to use. Thank you again. You can close this.
