### ISSUE TITLE
Custom fields support ?

### ISSUE THREAD

**Issue by mareban** [cblomart/vsphere-graphite#60]
Hello,

Very nice project :-) 

Is it possible to add custom fields please ?

ex : vsphere.virtualmachine.custom_fields.Owner  (the owner of the VM)

Thanks for your help.

**Comment by cblomart** [comment]
I don't quite see how you see that in vsphere-graphite? Maybe if you could describe a full "story" of what you want? (i.e. in your example where do you define the owner?)

Would vSphere tags be a response to the requirement? see issue #29

**Comment by mareban** [comment]
Sorry, i'm not the virtual envrionment admin :-) 

Metricbeat (beta, and very limited) do that by default  : https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-vsphere.html

vsphere.virtualmachine.custom_fields
type: object
Custom fields

https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.vcenterhost.doc/GUID-73606C4C-763C-4E27-A1DA-032E4C46219D.html

Maybe, tag can help.

Thanks for your help (Merci beaucoup :-) )

**Comment by cblomart** [comment]
I propose we follow up this issue on issue #29
