### ISSUE TITLE
Kibana Dashboard ?

### ISSUE THREAD

**Issue by mareban** [cblomart/vsphere-graphite#61]
Hello,

It works great, but do you have kibana (6.x)  dashboard template please ??

Thanks for your help.

**Comment by cblomart** [comment]
@MnrGreg: don't you use elasticsearch... would there be some dashboard template that can be shared?

**Comment by MnrGreg** [comment]
I use elastic yes, but have a personal preference for Grafana. There's no technical reason why one could develop the same in Kibana.

The Grafana dashboards are available here: https://grafana.com/dashboards/6902

Let me know if you would like the updated Cluster, Host and VM level dashboards.

**Comment by xkilian** [comment]
Anyone have dashboards for Grafana of the Prometheus exported metrics from vsphere-graphite.
I have created a VM level dashboard, but not for Host and Cluster level.

**Comment by xkilian** [comment]
I have published a vm level dashboard based on Prometheus datasource for vsphere-graphite, you can find it here : [https://grafana.com/dashboards/9929](https://grafana.com/dashboards/9929)

**Comment by cblomart** [comment]
Thanks @xkilian I will close this for now.
