### ISSUE TITLE
IP addresses for vCenter or hosts leads to undesired directory structures

### ISSUE THREAD

**Issue by ybizeul** [cblomart/vsphere-graphite#62]
https://github.com/cblomart/vsphere-graphite/blob/1824e2a467f21e6fd88b5acf35a44cdf4994e026/backend/backend.go#L244

If I understand that code correctly, this is why I'm getting `w/x/y/z/` directories in lieu of the hosts it's supposed to represent.

Why not replacing "." by "_" in `point.VCenter` and `point.ObjectName` ?

**Comment by ybizeul** [comment]
Thanks for your answer. Yes I think it would totally make sense to default to character replacement as dot character being used both in IPs and graphite separator is more like a hack if you want to split on subnet, only works with /24 /16 etc...

Now, having the option would certainly fix the issue too. I did implement it with success in my environment (after figuring out what the hell that musl gcc was :-))

I agree ip in vcenter is not best practice. My first reaction was to replace with fqdn and test... that “duh” moment when I realised that fqdns also have dots in them ! So I put the short name, make sure dns search is set to the domain, but then saw that the same thing happens with individual esx hosts (and I agree, using IP isn’t best practice there either but well...)

Thanks !

**Comment by ybizeul** [comment]
I would add that using `_` instead of `.` wouldn't be a big issue for people grouping by subnet as you can easily use wildcards anyway

**Comment by cblomart** [comment]
I added in the last commits a additional confg "ReplacePoint" which will tell vsphere-graphite to replace points with "_". You can set it to true or false and is false by default (absent).

Concerning fqdns and points in them... indeed they have points in them. There is a config param "Domain" who will strip the domain name from fqdns... so you only have the hostname.

You can test all this with docker and "cblomart/vsphere-graphite:b9a58f7".

I didn't have time to test it so: feedback welcome!!!

**Comment by cblomart** [comment]
@ybizeul were you able to test this?

**Comment by cblomart** [comment]
@ybizeul I will wait until Wednesday and close the issue. If you ever have time to provide some feedback, don’t hesitate and reply on the issue and/or reopen it.

**Comment by ybizeul** [comment]
Sorry I couldn’t test this, I will report as soon as I can though

**Comment by cblomart** [comment]
@scaleoutsean were you able to test the change implemented here? @ybizeul any news?

**Comment by ybizeul** [comment]
I'm not able to test in on the previous environment right now, I'm testing it in my lab.

Vanilla install is behaving how I expect it to behave, I suppose because I actually used a proper domain name and DNS names in my vSphere infrastructure in this lab.

So I added a typo do "Domain" key in vsphere-graphite config so it wouldn't match my domain anymore.

After that I got the directory path for each domain name members, for the vcenter as well as the ESX hosts. So far so good.

Added `"ReplacePoint": true` and :

![screenshot 2018-10-14 at 11 02 31](https://user-images.githubusercontent.com/182035/46914656-aa14b180-cfa0-11e8-9c5d-d29a2caaa558.png)

Tadaaa!

I think it's a great compromise and probably a good practice to incite people to use proper DNS in their vSphere infrastructure. I'm happy with the change.

Thanks!

**Comment by ybizeul** [comment]
For better English, maybe the option should be named `ReplaceDots` ?

**Comment by scaleoutsean** [comment]
> I'm not able to test in on the previous environment right now, I'm testing it in my lab.

I tried to test within hcicollector but couldn't integrate the image into that docker-compose (notably `sh` seems to be missing in the (minimalistic?) beta container image, but is present in hcicollector. 
@ybizeul did you test that beta container as standalone container? 

@cblomart: is this one test enough to release the patch so that we can try it downstream?
