### ISSUE TITLE
cant run vsphere-graphite

### ISSUE THREAD

**Issue by ridhoyp** [cblomart/vsphere-graphite#7]
2017/05/17 15:16:18 Starting daemon: vsphere-graphite
2017/05/17 15:16:18 connecting to vcenter: vcenterip
2017/05/17 15:16:18 Could not connect to vcenter:  vcenterip
2017/05/17 15:16:18 Error:  Post https://domain:password@vcenterip/sdk: dial tcp: unknown port tcp/Nutanix
2017/05/17 15:16:18 Could not connect to vcenter:  vcenterip
2017/05/17 15:16:18 Error:  Post : dial tcp: unknown port tcp/Nutanix
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x780ed8]

goroutine 1 [running]:
panic(0xa93d60, 0xc42000c0e0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/vmware/govmomi.(*Client).Logout(0x0, 0x11239e0, 0xc420052580, 0x0, 0x0)
        /var/lib/vmware/src/github.com/vmware/govmomi/client.go:140 +0x38
github.com/cblomart/vsphere-graphite/vsphere.(*VCenter).Init(0xc4200568c0, 0xc4200c6240, 0x3, 0x4, 0xc420056820, 0xc420056870)
        /var/lib/vmware/src/github.com/cblomart/vsphere-graphite/vsphere/vsphere.go:83 +0x1335
main.(*Service).Manage(0xc420195e88, 0x0, 0x0, 0x0, 0x0)
        /var/lib/vmware/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:114 +0x503
main.main()
        /var/lib/vmware/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:176 +0x10f

**Comment by cblomart** [comment]
This is due to the "/" in your password... you can escape it with html chars. you can replace it with "%2F"

**Comment by ridhoyp** [comment]
Hi cblomart, your so awesome! , thanks..
