### ISSUE TITLE
Slow down in metric submission to Elastic backend

### ISSUE THREAD

**Issue by MnrGreg** [cblomart/vsphere-graphite#72]
Commit 231ba50 has been working well with submission times of +-100k metrics to elastic backend completing in under 25 seconds. Subsequent builds have a lot slower submission times (taking around 2mins). Have there been any changes that could be affecting this?

_2019/01/18 06:07:13 Version information: - - 231ba50 (dirty)
2019/01/18 06:07:13 Starting daemon: vsphere-graphite
2019/01/18 06:07:13 Initializing vCenter rkvXX
2019/01/18 06:07:13 connecting to vcenter: rkvXX
2019/01/18 06:07:13 disconnecting from vcenter: rkvXX
2019/01/18 06:07:13 Initializing elastic backend monXX:9200/vsphere-graphitev2-2019.01.18
2019/01/18 06:07:14 Retrieving metrics
2019/01/18 06:07:14 Setting up query inventory of vcenter:  rkvXX
2019/01/18 06:07:14 connecting to vcenter: rkvXX
2019/01/18 06:07:16 Issuing 3657 queries to vcenter rkvXX requesting 69763 metrics.
2019/01/18 06:07:20 Got 3399 results from rkvXXwith 60595 values
2019/01/18 06:0**7:20** disconnecting from vcenter: rkvXX
2019/01/18 06:0**7:41** Logs successfully indexed:  99778
2019/01/18 06:07:41 Sent 99778 logs to backend
2019/01/18 06:07:41 Memory usage : sys=404.6M alloc=33M
2019/01/18 06:08:14 Scheduled metric retrieval_

**Comment by cblomart** [comment]
The first change to elastic i see after that is the pull request #68 in commit 3d1d68d
Can you confirm that this has the issue?

**Comment by cblomart** [comment]
Memory usage should be shoWn at the end of each cycle... if sending the logs to elastic is slowed down, they will be « slowed down » too...

**Comment by cblomart** [comment]
You do confirm that between 231ba50 and 3d1d68d there is a difference?

I do not so go vendor so it could also have to do with elastic golang implementation (i didn’t check)

**Comment by MnrGreg** [comment]
I've tried commits going all the way back to November for both vsphere-graphite and olivere/elastic. The problem seems to persist across all. Not sure if its some other modules that might have changed or what.

Interestingly I did notice that when I set the FlushSize to less than the total number of metrics, the first flush is very quick +-10 seconds. The subsequent flush takes +-15mins. 80k metrics are submitted in flush 1 while only the remaining 5k metrics are submitted in flush 2. So might it be some other function other than the actual Elastic submissions that is either waiting or looping?

_2019/01/19 05:14:39 Version information: NA - NA@NA (NA)
2019/01/19 05:14:39 Starting daemon: vsphere-graphite
2019/01/19 05:14:39 Initializing vCenter rkvxxx
2019/01/19 05:14:39 connecting to vcenter: rkvxxx
2019/01/19 05:14:39 disconnecting from vcenter: rkvxxx
2019/01/19 05:14:39 Initializing elastic backend monxxx:9200/vsphere-graphitev2-2019.01.19
2019/01/19 05:14:40 Retrieving metrics
2019/01/19 05:14:40 Setting up query inventory of vcenter:  rkvxxx
2019/01/19 05:14:40 connecting to vcenter: rkvxxx
2019/01/19 05:14:41 Issuing 1785 queries to vcenter rkvxxx requesting 34016 metrics.
2019/01/19 05:14:44 Got 1744 results from rkvxxx with 52566 values
2019/01/19 05:**14:44** disconnecting from vcenter: rkvxxx
2019/01/19 05:**14:56** Logs successfully indexed:  80000
2019/01/19 05:14:56 Elastic Indexing flushed
2019/01/19 05:**14:56** Sent 80000 logs to backend
2019/01/19 05:**31:03** Logs successfully indexed:  5269
2019/01/19 05:31:03 Elastic Indexing flushed
2019/01/19 05:31:03 Sent 5269 logs to backend
2019/01/19 05:31:03 Scheduled metric retrieval
2019/01/19 05:31:03 Setting up query inventory of vcenter:  rkvxxx
2019/01/19 05:31:03 connecting to vcenter: rkvxxx
2019/01/19 05:31:03 Memory usage : sys=337.1M alloc=24.4M
2019/01/19 05:31:04 Issuing 1785 queries to vcenter rkvxxxv requesting 34016 metrics.
2019/01/19 05:31:07 Got 1744 results from rkvxxx with 52566 values
2019/01/19 05:**31:07** disconnecting from vcenter: rkvxxx
2019/01/19 05:**31:20** Logs successfully indexed:  80000
2019/01/19 05:31:20 Elastic Indexing flushed
2019/01/19 05:**31:20** Sent 80000 logs to backend
2019/01/19 05:**45:42** Logs successfully indexed:  5263
2019/01/19 05:45:42 Elastic Indexing flushed
2019/01/19 05:45:42 Sent 5263 logs to backend
2019/01/19 05:45:42 Scheduled metric retrieval
2019/01/19 05:45:42 Setting up query inventory of vcenter:  rkvxxx

**Comment by cblomart** [comment]
I reviewed a bit the logging to see what happends.
SendMetrics is sent for each flushsize of metrics recieved.
To be sure to sent most of the metrics in the cycle a "latch" is setup to be sure to send the rest of metrics of no metrics are recieved in 5 seconds (memtimer). it is a timer that waits 5 seconds and is reset everytime a metric is recieved. It looks like metrics are still recieved for a long time... as the ```Sent 5263 logs to backend``` is only recieved later...

**Comment by cblomart** [comment]
I added some changes so the channel management may get « faster ». In fact in start input management in threads when possible.
The trought is that as it treats input of each queue in a while loop this treatment may delay timers... 
there is still something taking more time than usual..
Changes are found In elastic-slow branch. See also last docker push

**Comment by MnrGreg** [comment]
I've recently started restricting vsphere permissions to only certain vsphere datacenters and clusters in an attempt to reduce the overall number of metrics collected. Perhaps something there could be slowing down the tail end of the metrics collection process?

I tried the `elastic-slow` build and go a panic (seen below). 

```
2019/01/21 02:05:55 Version information: NA - 43428e3@elastic-slow (clean)
2019/01/21 02:05:55 Starting daemon: vsphere-graphite
2019/01/21 02:05:55 Initializing vCenter rkvxxx
2019/01/21 02:05:55 connecting to vcenter: rkvxxx
2019/01/21 02:05:55 disconnecting from vcenter: rkvxxx
2019/01/21 02:05:55 Initializing elastic backend monxxx:9200/vsphere-graphitev2-2019.01.21
2019/01/21 02:06:01 Retrieving metrics
2019/01/21 02:06:01 Setting up query inventory of vcenter:  rkvxxx
2019/01/21 02:06:01 connecting to vcenter: rkvxxx
2019/01/21 02:06:03 Issuing 1097 queries to vcenter rkvxxx requesting 20897 metrics.
panic: runtime error: racy use of timers

goroutine 20930 [running]:
time.startTimer(0xc000307778)
        /usr/local/go/src/runtime/time.go:114 +0x2b
time.(*Timer).Reset(0xc000307770, 0x12a05f200, 0x0)
        /usr/local/go/src/time/sleep.go:130 +0x81
main.(*Service).Manage.func1(0xc000307770, 0xc002009b00, 0xc001eb2000, 0x186a0, 0x186a0, 0xc0000afaf0, 0xc0001de480)
        /go/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:231 +0x5a
created by main.(*Service).Manage
        /go/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:223 +0x1626
```


Appreciate your help trying to work through all of this.

**Comment by cblomart** [comment]
i moved the timer reset out of the go func to avoid issues. (docker image cblomart/vsphere-graphite:929e932)

**Comment by cblomart** [comment]
Made some substential changes and rebuild a test vm to validate it... 
can you retest with: cblomart/vsphere-graphite:5a0cc76
Sorry for the ping/pong

**Comment by MnrGreg** [comment]
Just to follow up here. Seeing consistent performance now with 125k worth of metrics submitted in around 20secs.

```
2019/01/27 18:49:31 scheduled metric retrieval
2019/01/27 18:49:31 vcenter rkvxx: setting up query inventory
2019/01/27 18:49:31 vcenter rkvxx: connecting
2019/01/27 18:49:32 vcenter rkvxx: issuing 2674 queries requesting 50975 metrics.
2019/01/27 18:49:35 vcenter rkvxx: retuned 2577 metrics
2019/01/27 18:49:35 vcenter rkvxx: got 2577 results with 77902 values
2019/01/27 18:49:35 vcenter rkvxx: disconnecting
2019/01/27 18:49:40 sent last 125338 logs to backend
2019/01/27 18:49:40 Memory usage : sys=1.8G alloc=88.5M
2019/01/27 18:50:00 backend elastic: 125338 logs successfully indexed
```

**Comment by cblomart** [comment]
I will merge changes to master branch.
You may want to reset your flushsize to a lower value.
