### ISSUE TITLE
How to get CPU Ready per-VM ?

### ISSUE THREAD

**Issue by aventrax** [cblomart/vsphere-graphite#78]
Hello, I'm trying vsphere-graphite and on Grafana I can see the metrics coming.
Unfortunately I didn't get how to obtain per-VM CPU Ready times (or any other per-VM stat), because I can't select the VM name on the metric select list in grafana.

Is anything I'm missing? Is there any documentation about it?

Thanks

**Comment by cblomart** [comment]
Which backend are you using (elastic, influx, Prometheus)? Do you use an existing template in grafana or do you do your dashboard yourself?

**Comment by aventrax** [comment]
I'm using graphite, I (erroneously) thought it was the only backend supported by this project because of the name "vsphere-graphite" ;-) Is that kind of backend does not supported for per-VM stats? Why?

Just to try I can load the metrics to the elasticsearch backend that I have in place, but where do I get the template to load in ES?

**Comment by cblomart** [comment]
i didn't include any template... i recently created a template for prometheus.
Graphite does support per vm statistics, i wanted to check up because on issue #77 there seems to be some issues on metadata. 
As graphite have no metadata... it should not be related.

Did you use a template to build your dashboard?

**Comment by aventrax** [comment]
I'm creating my graph from scratch but I cannot see any per-VM stat. Indeed I can't get any meaning for cpu cpu ready not associated to a VM "object".
To be more clear, I searched in /var/lib/graphite/whisper/ where there are the .wsp files, but there is nothing per-VM. I have only /var/lib/graphite/whisper/vsphere/MY-VCENTER/virtualmachine/cpu/ready/summation.wsp but nothing more. Why is it "global"? the /virtualmachine/ folder is NOT a VM that I defined, it seems part of the tree.

**Comment by aventrax** [comment]
Update: I tried an old version: vsphere-graphite_linux_amd64_v0.5.tgz

It works!

**Comment by cblomart** [comment]
Ok, i tried to implement a limit on graphite and there was a bug in it preventing to collect names of entities.
The limit is in place as graphite doesn't have metadata and doesn't need to collect plentity of extra infromations from vsphere.

Can you test with 05a4dc5 ?

**Comment by aventrax** [comment]
Working!Thanks!
