### ISSUE TITLE
Publish or link to Grafana Dashboard (prometheus datasource)

### ISSUE THREAD

**Issue by xkilian** [cblomart/vsphere-graphite#82]
You mentioned you had a Prometheus Grafana Template. Can you publish it on Grafana and link to it in the readme.
I am building a vm-level statsdasboard, I also have started working on some cluster level dashboards. I am hoping someone had vm-level,  cluster or datacenter level dashboards built and is willing to share them. I will share what I have when finished.
Second the Readme does not mention Prometheus support and does not provide documentation on what parameters are supported. I had to look in the source code to figure it out. :-)
ps. The new releases of this with Prometheus with all the tags, are simply phenomenal, very good work. Thank you.

**Comment by MnrGreg** [comment]
@xkilian, which tags are you referring to?

**Comment by cblomart** [comment]
I will take the time today to publish the basic dashboard i have for virtual machines.
Looking at readme now i suppose you are refering to the backend parameters section.

@MnrGreg : no vsphere tag support is not there yet.... i think @xkilian refers to tags in the prometheus output (host, datastore, network, ...)

**Comment by cblomart** [comment]
The dashboard is published https://grafana.com/dashboards/9925

Need to work on readme there.

**Comment by xkilian** [comment]
Yeah, I was mentioning tags in the Prometheus context. Yes to the backend section as well, that is what was missing, as well as simply mentioning in the readme that Prometheus is supported. ;-) Even our Vrealize users like the output that Grafana + Prometheus + Vsphere_graphite gives.
I will look at the dashboard and provide feedback or improvements.

**Comment by xkilian** [comment]
I published an updated dashboard that uses vsphere-graphite and Prometheus backend. [https://grafana.com/dashboards/9929](https://grafana.com/dashboards/9929)
The 9925 dashboard you published could not be cleanly imported.

**Comment by xkilian** [comment]
You could test the dashboard and link to it in the readme. I will let you know when the other dashboards are ready.

**Comment by Teriand** [comment]
> I published an updated dashboard that uses vsphere-graphite and Prometheus backend. https://grafana.com/dashboards/9929
> The 9925 dashboard you published could not be cleanly imported.

How json using for this dashboard?

**Comment by xkilian** [comment]
In Grafana, you can go to the dashboards list and select import from file. Lookup importing dashboards in the Grafana documentation. It is very easy to do. The only constraints are that you need a prometheus datasource with the sphere-graphite data.
Cheers,

**Comment by Teriand** [comment]
No, i get answer for question, dashboard using for default json for vsphere-graphite. thx

**Comment by cblomart** [comment]
i guess this is solved... closing for now (react if not!)
