### ISSUE TITLE
Could not decode configuration file Error: Invalid character 'y' looking for beginning of value

### ISSUE THREAD

**Issue by jedimt** [cblomart/vsphere-graphite#88]
When building the container I'm getting the error listed in the description. My vsphere-graphite.json file doesn't appear to have any stray 'y' characters. 

root@sfps-grafana-dev:/opt/github/hcicollector# docker-compose up --no-deps --build vmwcollector
Building vmwcollector
Step 1/3 : FROM cblomart/vsphere-graphite:latest
 ---> 2306365f42f2
Step 2/3 : COPY vsphere-graphite.json /etc/vsphere-graphite.json
 ---> a988e1564104
Step 3/3 : ENTRYPOINT [ "/vsphere-graphite" ]
 ---> Running in ba93cc3d0b5d
Removing intermediate container ba93cc3d0b5d
 ---> f965f171715e
Successfully built f965f171715e
Successfully tagged hcicollector_vmwcollector:latest
Recreating vmwcollector-v.6
Attaching to vmwcollector-v.6
vmwcollector-v.6 | 2019/04/04 12:24:22 Version information: NA - a713caa@HEAD (dirty)
vmwcollector-v.6 | 2019/04/04 12:24:22 Starting daemon: vsphere-graphite
vmwcollector-v.6 | 2019/04/04 12:24:22 Could not decode configuration file Error:  invalid character 'y' looking for beginning of value
vmwcollector-v.6 exited with code 1

**Comment by jedimt** [comment]
Rebuilding my docker host seems to have fixed this. Not sure what the exact issue was. Please disregard.

**Comment by cblomart** [comment]
Everubody loves these autosolved issues :)

I hope vsphere-graphite does help you well!
