### ISSUE TITLE
best template using vsphere-graphite or influxdb for grafana

### ISSUE THREAD

**Issue by ridhoyp** [cblomart/vsphere-graphite#9]
Hi,

i use influxdb to store the metrics

but some of metrics has empty value especially the metrics with average name so i use metrics with max, i already use https://grafana.com/dashboards/1299 but still dont satisfied, because there is no network statistics, cant query the net_received_average,

can you help to trace the metrics with average name? why its not captured, or should i use max?

Regards,
RidhoYP

**Comment by cblomart** [comment]
I'd like to first check issue #8 before continuing on empty averages and net.recieved.average.

Cédric

**Comment by cblomart** [comment]
Ok,

I am able to get net usage by adding this to the VirtualMachine collected metrics:
{ "Metric": "net.recieved.average", "Instance": "*" }

The trick is that net usage is counted by instance.

**Comment by ridhoyp** [comment]
Hi

here is the default query from dashboard : SELECT mean("net_received_average") FROM "virtualmachine" WHERE "name" =~ /^$vmname$/ AND $timeFilter GROUP BY time($interval), "name" fill(null)

it can be applied?

if you can query like that, what i must check from my side? 

Thanks :)

Regards,
RidhoYP

**Comment by ridhoyp** [comment]
Hi,

Yea, i thought you using influxdb too , so i post it :)

yea thats influx query, when using your script but write to influxdb, 

i just want the dashboard function works 100%, but seems i must learn more how to do it :) and what i want to grab 

Regards,
RidhoYP

**Comment by cblomart** [comment]
Concerning the influxdb query... after further tests... the query should look like:
SELECT mean("Value") FROM "net_received_average" WHERE "name" =~ /^$vmname$/ AND $timeFilter GROUP BY time($interval), "name" fill(null)

**Comment by cblomart** [comment]
In the last update you can, if needed, change the name of the field holding the value.

Do you now have a proper solution to the issue?
