### ISSUE TITLE
Default Configuration issue

### ISSUE THREAD

**Issue by reamasesa** [cblomart/vsphere-graphite#97]
Hello,

I'm trying to pull metrics from our VCenter but I'm getting empty responses
I'm using the default configuration file, just changed the VCenter specific properties (username, password, the likes), using Prometheus as the backend
If any information is missing, let me know and I'll provide it
It's probably a configuration directive I'm not aware of

Thanks

2019/07/01 15:38:30 vcenter 1.1.1.1: setting up query inventory
2019/07/01 15:38:30 vcenter 1.1.1.1: connecting
2019/07/01 15:38:30 vcenter 1.1.1.1: skipped 0 objects because they are either not connected or not powered on
2019/07/01 15:38:30 vcenter 1.1.1.1: 2 objects (0 vm and 2 hosts)
2019/07/01 15:38:30 vcenter 1.1.1.1: queries generated
2019/07/01 15:38:30 vcenter 1.1.1.1: 2 queries
2019/07/01 15:38:30 vcenter 1.1.1.1: 34 total metricIds
2019/07/01 15:38:30 vcenter 1.1.1.1: 102 total counter (accounting for 3 instances ratio)
2019/07/01 15:38:30 vcenter 1.1.1.1: created batch 0 from queries 1 - 2
2019/07/01 15:38:30 vcenter 1.1.1.1: 1 threads generated to execute queries
2019/07/01 15:38:30 vcenter 1.1.1.1: thread 1 requests 2 metrics
2019/07/01 15:38:30 vcenter 1.1.1.1 thread 1: requesting 2 metrics
2019/07/01 15:38:30 vcenter 1.1.1.1 thread 1: no result returned by queries
2019/07/01 15:38:30 vcenter 1.1.1.1: disconnecting

**Comment by cblomart** [comment]
Maybe not directly related but it looks like vsphere-graphite doens't see any vms... ```(0 vm and 2 hosts)```

Is this intended?

And effectively there is no result to perf queries ```no result returned by queries``` ...

Could you share the metrics shown int your config file?

**Comment by reamasesa** [comment]
> Maybe not directly related but it looks like vsphere-graphite doens't see any vms... (0 vm and 2 hosts)
> Is this intended?
> And effectively there is no result to perf queries no result returned by queries ...
> Could you share the metrics shown int your config file?

Thanks for replying
No, it's not intentional, as far as I know the monitoring user has read only to everything and I also tried with the administrator account and still go t the same results. Is there anything I need to do on the VCenterside to enable it?

My metrics are the default ones from the example here, if we're at it, how do I know which metrics are exposed by the VCenter?


Here they are:

` "Metrics": [

    { 

      "ObjectType": [ "VirtualMachine", "HostSystem" ], 

      "Definition": [

        { "Metric": "cpu.usage.average", "Instances": "" },

        { "Metric": "cpu.usage.maximum", "Instances": "" },

        { "Metric": "cpu.usagemhz.average", "Instances": "" },

        { "Metric": "cpu.usagemhz.maximum", "Instances": "" },

        { "Metric": "cpu.totalCapacity.average", "Instances": "" },

        { "Metric": "mem.usage.average", "Instances": "" },

        { "Metric": "mem.usage.maximum", "Instances": "" },

        { "Metric": "mem.consumed.average", "Instances": "" },

        { "Metric": "mem.consumed.maximum", "Instances": "" },

        { "Metric": "mem.active.average", "Instances": "" },

        { "Metric": "mem.active.maximum", "Instances": "" },

        { "Metric": "mem.vmmemctl.average", "Instances": "" },

        { "Metric": "mem.vmmemctl.maximum", "Instances": "" },

        { "Metric": "mem.totalCapacity.average", "Instances": "" }

      ]

    },

    { 

      "ObjectType": [ "VirtualMachine" ], 

      "Definition": [

        { "Metric": "virtualDisk.totalWriteLatency.average", "Instances": "*" },

        { "Metric": "virtualDisk.totalReadLatency.average", "Instances": "*" },

        { "Metric": "virtualDisk.numberReadAveraged.average", "Instances": "*" },

        { "Metric": "virtualDisk.numberWriteAveraged.average", "Instances": "*" },

        { "Metric": "cpu.ready.summation", "Instance": ""}

      ]

    },

    { 

      "ObjectType": [ "HostSystem" ], 

      "Definition": [

        { "Metric": "disk.maxTotalLatency.latest", "Instances": "" },

        { "Metric": "disk.numberReadAveraged.average", "Instances": "*" },

        { "Metric": "disk.numberWriteAveraged.average", "Instances": "*" }

      ]

    }

  ]
`

**Comment by reamasesa** [comment]
Closed it by accident, sorry :(

**Comment by cblomart** [comment]
HostSystems that are found should at least return some values.

You did try to log in vcenter with the user and check that you can consult realtime performances of host and virtual machines, didn't you?

**Comment by reamasesa** [comment]
> HostSystems that are found should at least return some values.
> 
> You did try to log in vcenter with the user and check that you can consult realtime performances of host and virtual machines, didn't you?

Sorry for the delay, I was a bit sick and had to rest
Yes, I logged in with the user and the user was able to see the performance and other information the ReadOnly Role allows, I also tried using the Administrator account in the vsphere-graphite configuration thinking maybe I need more permission I'm not aware of but it, too, ended up with same results

**Comment by cblomart** [comment]
Ok... sounds strange to me (also)... could you indicate which version of vcenter you have?

**Comment by reamasesa** [comment]
Hi,

We're using 6.7 in our setup


Thanks

**Comment by reamasesa** [comment]
Hi,

Any updates on this? Could you recommend a configuration change that might work for us?


Thanks

**Comment by cblomart** [comment]
Can you install [govc](https://github.com/vmware/govmomi/tree/master/govc) and check the result of the following command
```bash
> govc find
```

**Comment by cblomart** [comment]
@reamasesa : did you have any time to test this?

**Comment by reamasesa** [comment]
> @reamasesa : did you have any time to test this?

Hi,
No, not yet, both rack and myself are still on route to destination, when we've both landed I'll post the results

Thanks for the help

**Comment by reamasesa** [comment]
> Can you install [govc](https://github.com/vmware/govmomi/tree/master/govc) and check the result of the following command
> 
> ```shell
> > govc find
> ```

Hello,

Thank you for your patience with this, here's the output of the command, I had to change the names of the datastore, networks and VM names as they are way too descriptive :)


~$ ./govc_linux_amd64 find
/
/External
/External/vm
/External/host
/External/datastore
/External/network
/External/network/LAN
/External/network/LAN1
/External/network/LAN2
/External/network/LAN3
/External/network/LAN4
/External/network/LAN5
/External/network/LAN6
/External/network/LAN7
/External/datastore/datastore1
/External/datastore/datastore2
/External/datastore/datastore3
/External/datastore/datastore4
/External/datastore/datastore5
/External/datastore/datastore6
/External/datastore/datastore7
/External/host/Cluster1
/External/host/Cluster1/Resources
/External/host/Cluster1/10.10.10.1
/External/host/Cluster1/10.10.10.2
/External/vm/VM1
/External/vm/VM2
/External/vm/VM3
/External/vm/VM4
/External/vm/VM5
/External/vm/VM6
/External/vm/VM6/VM1
/External/vm/VM7
/External/vm/VM7/VM1
/External/vm/VM8
/External/vm/VM8/VM1
/External/vm/VM9/VM1
/External/vm/VM10/VM1
/External/vm/VM11/VM1
/External/vm/VM12/VM1
/External/vm/VM12/VM2
/External/vm/VM13

**Comment by reamasesa** [comment]
Hi,

I think I'm making some progress, and the issue was somehow related to network connectivity and I can see entries in prometheus starting with vsphere_
I'm sorry but I couldn't find any mention in the examples and samples on how to gather all the information the VCenter can export using the vcenter-graphite exporter, if you could direct me to where I can see a sample of a "get * out of everything" configuration it would be very much appreciated

**Comment by cblomart** [comment]
Nice to hear that you got further.
About the available metrics, I didn’t list the metrics because it totally depends on VMware. Normally any real time metrics available to host and vms should be available.
If you checkout the sphere management interface you should get a view of available metrics and instances via the advanced performances.

**Comment by reamasesa** [comment]
> Nice to hear that you got further.
> About the available metrics, I didn’t list the metrics because it totally depends on VMware. Normally any real time metrics available to host and vms should be available.
> If you checkout the sphere management interface you should get a view of available metrics and instances via the advanced performances.

Thanks, I went to the Performance->Advanced menu but couldn't decipher how to convert/see the graphs legends to something like "mem.totalCapacity.average" that is shown in the default configuration

Is there a way to get all the metrics names and relativity for the VMs, cluster(s) and hosts? I tried the links to the VMware documentation but couldn't find any mentioning of anything like the "mem.totalCapacity.average" directive

Sorry if it's a lame question, I'm fairly new to all of this

**Comment by reamasesa** [comment]
Closing this issue as it was network related

Also, if anyone happens to stumble upon this issue and is clueless as I am regarding the metrics exposed by the VCenter

govc metric.ls should help

**Comment by cblomart** [comment]
Do you have the output of govc metrics.ls ? Maybe I can add it to the doc...

**Comment by reamasesa** [comment]
> Do you have the output of govc metrics.ls ? Maybe I can add it to the doc...

Sure, I'll post it later on, I think metrics.info is actually better, I'll compare the output and post the better one

Right now, I'm still having issues with polling the ESX, it's working from govc metric.sample but not from vsphere-graphite

2019/08/13 00:12:07 Starting daemon: vsphere-graphite
2019/08/13 00:12:07 main: requested properties folder, tags, host, cluster, network, resourcepool, numcpu, memorysizemb, disks, datastore, urls
2019/08/13 00:12:07 vcenter 10: initializing
2019/08/13 00:12:07 vcenter 10: connecting
2019/08/13 00:12:07 vcenter 10: disconnecting
2019/08/13 00:12:07 backend prometheus: initializing
2019/08/13 00:12:07 backend prometheus: starting listener on :9102
2019/08/13 00:12:58 prometheus: requesting metrics
2019/08/13 00:12:58 prometheus: requested metrics
2019/08/13 00:12:58 adhoc metric retrieval
2019/08/13 00:12:58 vcenter 10.1.1.1: setting up query inventory
2019/08/13 00:12:58 vcenter 10: connecting
2019/08/13 00:12:58 vcenter 10.1.1.1: skipped 0 objects because they are either not connected or not powered on
2019/08/13 00:12:58 vcenter 10.1.1.1: 2 objects (1 vm and 1 hosts)
2019/08/13 00:12:58 vcenter 10.1.1.1: queries generated
2019/08/13 00:12:58 vcenter 10.1.1.1: 2 queries
2019/08/13 00:12:58 vcenter 10.1.1.1: 2 total metricIds
2019/08/13 00:12:58 vcenter 10.1.1.1: 6 total counter (accounting for 3 instances ratio)
2019/08/13 00:12:58 vcenter 10.1.1.1: created batch 0 from queries 1 - 2
2019/08/13 00:12:58 vcenter 10.1.1.1: 1 threads generated to execute queries
2019/08/13 00:12:58 vcenter 10.1.1.1: thread 1 requests 2 metrics
2019/08/13 00:12:58 vcenter 10.1.1.1 thread 1: requesting 2 metrics
2019/08/13 00:12:58 vcenter 10.1.1.1 thread 1: no result returned by queries
2019/08/13 00:12:58 vcenter 10.1.1.1: disconnecting
2019/08/13 00:12:58 memory usage: sys=69.2M alloc=1.5M
2019/08/13 00:12:58 go routines: 9
2019/08/13 00:12:58 prometheus: sent 0 points

./govc metric.sample vm/* sys.uptime.latest
vm1  -  sys.uptime.latest    671871,671891,671911,671931,671951,671971  s

It's working on one ESX but not the other, as far as I can tell, they are identical, including the physical switch ports configuration, if you have any ideas for me to check, it would be great as I'm at a bit of a loss here

**Comment by reamasesa** [comment]
Closing this one as I no longer have access to the rack cabinet with the system
